title: Santhosh M Shet
description: Oracle CPQ Developer | CRM Solutions | Tech Enthusiast
theme: jekyll-theme-cayman

show_downloads: false

author: Santhosh M Shet
email: santhoshmshet94@gmail.com
linkedin: https://linkedin.com/in/santhoshshet
github: https://github.com/santhosh-shet
